/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mirte_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};

/* mirte_expl_ode_fun:(i0[7],i1[4],i2[3])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+1, w2, w3, w4, w5, w6, *w7=w+10, w8, w9;
  const casadi_real *cs;
  /* #0: @0 = -0.00016598 */
  w0 = -1.6598000000000001e-04;
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), cs=w1+0; cs!=w1+1; cs+=1) *rr++ = *cs;
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @3 = 0.00044484 */
  w3 = 4.4484000000000000e-04;
  /* #5: @4 = @1[1] */
  for (rr=(&w4), cs=w1+1; cs!=w1+2; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3*@4) */
  w3 *= w4;
  /* #7: @0 = (@0-@3) */
  w0 -= w3;
  /* #8: @3 = 0.00028542 */
  w3 = 2.8541999999999999e-04;
  /* #9: @5 = @1[2] */
  for (rr=(&w5), cs=w1+2; cs!=w1+3; cs+=1) *rr++ = *cs;
  /* #10: @3 = (@3*@5) */
  w3 *= w5;
  /* #11: @0 = (@0+@3) */
  w0 += w3;
  /* #12: @3 = 0.00021938 */
  w3 = 2.1938000000000000e-04;
  /* #13: @6 = @1[3] */
  for (rr=(&w6), cs=w1+3; cs!=w1+4; cs+=1) *rr++ = *cs;
  /* #14: @3 = (@3*@6) */
  w3 *= w6;
  /* #15: @0 = (@0+@3) */
  w0 += w3;
  /* #16: @3 = 0.00052793 */
  w3 = 5.2793000000000002e-04;
  /* #17: @7 = input[0][0] */
  casadi_copy(arg[0], 3, w7);
  /* #18: @8 = @7[2] */
  for (rr=(&w8), cs=w7+2; cs!=w7+3; cs+=1) *rr++ = *cs;
  /* #19: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #20: @3 = (@3*@9) */
  w3 *= w9;
  /* #21: @3 = (@3*@2) */
  w3 *= w2;
  /* #22: @0 = (@0+@3) */
  w0 += w3;
  /* #23: @3 = 0.0022203 */
  w3 = 2.2203000000000001e-03;
  /* #24: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #25: @3 = (@3*@8) */
  w3 *= w8;
  /* #26: @3 = (@3*@2) */
  w3 *= w2;
  /* #27: @0 = (@0+@3) */
  w0 += w3;
  /* #28: @3 = 0.00066344 */
  w3 = 6.6343999999999995e-04;
  /* #29: @3 = (@3*@9) */
  w3 *= w9;
  /* #30: @3 = (@3*@4) */
  w3 *= w4;
  /* #31: @0 = (@0-@3) */
  w0 -= w3;
  /* #32: @3 = 0.0023484 */
  w3 = 2.3484000000000001e-03;
  /* #33: @3 = (@3*@8) */
  w3 *= w8;
  /* #34: @3 = (@3*@4) */
  w3 *= w4;
  /* #35: @0 = (@0+@3) */
  w0 += w3;
  /* #36: @3 = 0.00087885 */
  w3 = 8.7885000000000003e-04;
  /* #37: @3 = (@3*@9) */
  w3 *= w9;
  /* #38: @3 = (@3*@5) */
  w3 *= w5;
  /* #39: @0 = (@0+@3) */
  w0 += w3;
  /* #40: @3 = 0.0013426 */
  w3 = 1.3426000000000000e-03;
  /* #41: @3 = (@3*@8) */
  w3 *= w8;
  /* #42: @3 = (@3*@5) */
  w3 *= w5;
  /* #43: @0 = (@0+@3) */
  w0 += w3;
  /* #44: @3 = 0.00075726 */
  w3 = 7.5726000000000005e-04;
  /* #45: @3 = (@3*@9) */
  w3 *= w9;
  /* #46: @3 = (@3*@6) */
  w3 *= w6;
  /* #47: @0 = (@0-@3) */
  w0 -= w3;
  /* #48: @3 = 0.00081618 */
  w3 = 8.1618000000000001e-04;
  /* #49: @3 = (@3*@8) */
  w3 *= w8;
  /* #50: @3 = (@3*@6) */
  w3 *= w6;
  /* #51: @0 = (@0+@3) */
  w0 += w3;
  /* #52: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #53: @0 = 0.0004803 */
  w0 = 4.8030000000000002e-04;
  /* #54: @0 = (@0*@2) */
  w0 *= w2;
  /* #55: @3 = 0.000149 */
  w3 = 1.4899999999999999e-04;
  /* #56: @3 = (@3*@4) */
  w3 *= w4;
  /* #57: @0 = (@0+@3) */
  w0 += w3;
  /* #58: @3 = 0.00029443 */
  w3 = 2.9442999999999998e-04;
  /* #59: @3 = (@3*@5) */
  w3 *= w5;
  /* #60: @0 = (@0-@3) */
  w0 -= w3;
  /* #61: @3 = 0.00045783 */
  w3 = 4.5783000000000000e-04;
  /* #62: @3 = (@3*@6) */
  w3 *= w6;
  /* #63: @0 = (@0-@3) */
  w0 -= w3;
  /* #64: @3 = 0.0013242 */
  w3 = 1.3242000000000000e-03;
  /* #65: @3 = (@3*@9) */
  w3 *= w9;
  /* #66: @3 = (@3*@2) */
  w3 *= w2;
  /* #67: @0 = (@0+@3) */
  w0 += w3;
  /* #68: @3 = 0.00085305 */
  w3 = 8.5305000000000005e-04;
  /* #69: @3 = (@3*@8) */
  w3 *= w8;
  /* #70: @3 = (@3*@2) */
  w3 *= w2;
  /* #71: @0 = (@0-@3) */
  w0 -= w3;
  /* #72: @3 = 0.0016074 */
  w3 = 1.6073999999999999e-03;
  /* #73: @3 = (@3*@9) */
  w3 *= w9;
  /* #74: @3 = (@3*@4) */
  w3 *= w4;
  /* #75: @0 = (@0+@3) */
  w0 += w3;
  /* #76: @3 = 0.00068381 */
  w3 = 6.8380999999999997e-04;
  /* #77: @3 = (@3*@8) */
  w3 *= w8;
  /* #78: @3 = (@3*@4) */
  w3 *= w4;
  /* #79: @0 = (@0+@3) */
  w0 += w3;
  /* #80: @3 = 0.0023134 */
  w3 = 2.3134000000000002e-03;
  /* #81: @3 = (@3*@9) */
  w3 *= w9;
  /* #82: @3 = (@3*@5) */
  w3 *= w5;
  /* #83: @0 = (@0+@3) */
  w0 += w3;
  /* #84: @3 = 0.00074272 */
  w3 = 7.4271999999999999e-04;
  /* #85: @3 = (@3*@8) */
  w3 *= w8;
  /* #86: @3 = (@3*@5) */
  w3 *= w5;
  /* #87: @0 = (@0-@3) */
  w0 -= w3;
  /* #88: @3 = 0.0021253 */
  w3 = 2.1253000000000001e-03;
  /* #89: @3 = (@3*@9) */
  w3 *= w9;
  /* #90: @3 = (@3*@6) */
  w3 *= w6;
  /* #91: @0 = (@0+@3) */
  w0 += w3;
  /* #92: @3 = 0.00088697 */
  w3 = 8.8696999999999995e-04;
  /* #93: @3 = (@3*@8) */
  w3 *= w8;
  /* #94: @3 = (@3*@6) */
  w3 *= w6;
  /* #95: @0 = (@0+@3) */
  w0 += w3;
  /* #96: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #97: @0 = -0.0043797 */
  w0 = -4.3797000000000003e-03;
  /* #98: @0 = (@0*@2) */
  w0 *= w2;
  /* #99: @3 = 0.008181 */
  w3 = 8.1810000000000008e-03;
  /* #100: @3 = (@3*@4) */
  w3 *= w4;
  /* #101: @0 = (@0+@3) */
  w0 += w3;
  /* #102: @3 = 0.0046648 */
  w3 = 4.6648000000000002e-03;
  /* #103: @3 = (@3*@5) */
  w3 *= w5;
  /* #104: @0 = (@0+@3) */
  w0 += w3;
  /* #105: @3 = 0.0078721 */
  w3 = 7.8720999999999999e-03;
  /* #106: @3 = (@3*@6) */
  w3 *= w6;
  /* #107: @0 = (@0-@3) */
  w0 -= w3;
  /* #108: @3 = 7.1607e-05 */
  w3 = 7.1606999999999994e-05;
  /* #109: @3 = (@3*@2) */
  w3 *= w2;
  /* #110: @3 = (@3*@2) */
  w3 *= w2;
  /* #111: @0 = (@0-@3) */
  w0 -= w3;
  /* #112: @3 = 7.2158e-05 */
  w3 = 7.2157999999999996e-05;
  /* #113: @3 = (@3*@2) */
  w3 *= w2;
  /* #114: @3 = (@3*@4) */
  w3 *= w4;
  /* #115: @0 = (@0-@3) */
  w0 -= w3;
  /* #116: @3 = 0.00011008 */
  w3 = 1.1008000000000000e-04;
  /* #117: @3 = (@3*@2) */
  w3 *= w2;
  /* #118: @3 = (@3*@5) */
  w3 *= w5;
  /* #119: @0 = (@0+@3) */
  w0 += w3;
  /* #120: @3 = 1.6506e-05 */
  w3 = 1.6506000000000001e-05;
  /* #121: @3 = (@3*@2) */
  w3 *= w2;
  /* #122: @3 = (@3*@6) */
  w3 *= w6;
  /* #123: @0 = (@0+@3) */
  w0 += w3;
  /* #124: @3 = 5.1765e-05 */
  w3 = 5.1765000000000003e-05;
  /* #125: @3 = (@3*@4) */
  w3 *= w4;
  /* #126: @3 = (@3*@5) */
  w3 *= w5;
  /* #127: @0 = (@0+@3) */
  w0 += w3;
  /* #128: @3 = 2.1046e-05 */
  w3 = 2.1046000000000001e-05;
  /* #129: @3 = (@3*@4) */
  w3 *= w4;
  /* #130: @3 = (@3*@6) */
  w3 *= w6;
  /* #131: @0 = (@0-@3) */
  w0 -= w3;
  /* #132: @3 = 3.0088e-05 */
  w3 = 3.0088000000000001e-05;
  /* #133: @3 = (@3*@5) */
  w3 *= w5;
  /* #134: @3 = (@3*@5) */
  w3 *= w5;
  /* #135: @0 = (@0-@3) */
  w0 -= w3;
  /* #136: @3 = 2.7602e-05 */
  w3 = 2.7602000000000001e-05;
  /* #137: @3 = (@3*@6) */
  w3 *= w6;
  /* #138: @3 = (@3*@6) */
  w3 *= w6;
  /* #139: @0 = (@0+@3) */
  w0 += w3;
  /* #140: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #141: @1 = input[1][0] */
  casadi_copy(arg[1], 4, w1);
  /* #142: output[0][3] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+3);
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mirte_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mirte_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mirte_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mirte_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mirte_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mirte_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mirte_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 15*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
