/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mirte_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {11, 1, 1};

/* mirte_expl_vde_adj:(i0[7],i1[7],i2[4],i3[3])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, *w01=w+3, w02, w03, w04, *w05=w+9, w06, *w07=w+14, w08, w09, w10;
  casadi_real *w11=w+24, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33;
  const casadi_real *cs;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w01);
  /* #2: @2 = @1[2] */
  for (rr=(&w02), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = 0.0021253 */
  w04 = 2.1253000000000001e-03;
  /* #5: @5 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w05);
  /* #6: @6 = @5[3] */
  for (rr=(&w06), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #7: @7 = input[1][0] */
  casadi_copy(arg[1], 7, w07);
  /* #8: {@8, @9, @10, @11} = vertsplit(@7) */
  w08 = w07[0];
  w09 = w07[1];
  w10 = w07[2];
  casadi_copy(w07+3, 4, w11);
  /* #9: @12 = (@6*@9) */
  w12  = (w06*w09);
  /* #10: @13 = (@4*@12) */
  w13  = (w04*w12);
  /* #11: @13 = (@3*@13) */
  w13  = (w03*w13);
  /* #12: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #13: @14 = 0.00088697 */
  w14 = 8.8696999999999995e-04;
  /* #14: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #15: @12 = (@2*@12) */
  w12  = (w02*w12);
  /* #16: @13 = (@13-@12) */
  w13 -= w12;
  /* #17: @12 = 0.00074272 */
  w12 = 7.4271999999999999e-04;
  /* #18: @15 = @5[2] */
  for (rr=(&w15), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #19: @16 = (@15*@9) */
  w16  = (w15*w09);
  /* #20: @17 = (@12*@16) */
  w17  = (w12*w16);
  /* #21: @17 = (@2*@17) */
  w17  = (w02*w17);
  /* #22: @13 = (@13+@17) */
  w13 += w17;
  /* #23: @17 = 0.0023134 */
  w17 = 2.3134000000000002e-03;
  /* #24: @16 = (@17*@16) */
  w16  = (w17*w16);
  /* #25: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #26: @13 = (@13+@16) */
  w13 += w16;
  /* #27: @16 = 0.00068381 */
  w16 = 6.8380999999999997e-04;
  /* #28: @18 = @5[1] */
  for (rr=(&w18), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #29: @19 = (@18*@9) */
  w19  = (w18*w09);
  /* #30: @20 = (@16*@19) */
  w20  = (w16*w19);
  /* #31: @20 = (@2*@20) */
  w20  = (w02*w20);
  /* #32: @13 = (@13-@20) */
  w13 -= w20;
  /* #33: @20 = 0.0016074 */
  w20 = 1.6073999999999999e-03;
  /* #34: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #35: @19 = (@3*@19) */
  w19  = (w03*w19);
  /* #36: @13 = (@13+@19) */
  w13 += w19;
  /* #37: @19 = 0.00085305 */
  w19 = 8.5305000000000005e-04;
  /* #38: @21 = @5[0] */
  for (rr=(&w21), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #39: @22 = (@21*@9) */
  w22  = (w21*w09);
  /* #40: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #41: @23 = (@2*@23) */
  w23  = (w02*w23);
  /* #42: @13 = (@13+@23) */
  w13 += w23;
  /* #43: @23 = 0.0013242 */
  w23 = 1.3242000000000000e-03;
  /* #44: @22 = (@23*@22) */
  w22  = (w23*w22);
  /* #45: @22 = (@3*@22) */
  w22  = (w03*w22);
  /* #46: @13 = (@13+@22) */
  w13 += w22;
  /* #47: @22 = 0.00081618 */
  w22 = 8.1618000000000001e-04;
  /* #48: @24 = (@6*@8) */
  w24  = (w06*w08);
  /* #49: @25 = (@22*@24) */
  w25  = (w22*w24);
  /* #50: @25 = (@2*@25) */
  w25  = (w02*w25);
  /* #51: @13 = (@13-@25) */
  w13 -= w25;
  /* #52: @25 = 0.00075726 */
  w25 = 7.5726000000000005e-04;
  /* #53: @24 = (@25*@24) */
  w24  = (w25*w24);
  /* #54: @24 = (@3*@24) */
  w24  = (w03*w24);
  /* #55: @13 = (@13-@24) */
  w13 -= w24;
  /* #56: @24 = 0.0013426 */
  w24 = 1.3426000000000000e-03;
  /* #57: @26 = (@15*@8) */
  w26  = (w15*w08);
  /* #58: @27 = (@24*@26) */
  w27  = (w24*w26);
  /* #59: @27 = (@2*@27) */
  w27  = (w02*w27);
  /* #60: @13 = (@13-@27) */
  w13 -= w27;
  /* #61: @27 = 0.00087885 */
  w27 = 8.7885000000000003e-04;
  /* #62: @26 = (@27*@26) */
  w26  = (w27*w26);
  /* #63: @26 = (@3*@26) */
  w26  = (w03*w26);
  /* #64: @13 = (@13+@26) */
  w13 += w26;
  /* #65: @26 = 0.0023484 */
  w26 = 2.3484000000000001e-03;
  /* #66: @28 = (@18*@8) */
  w28  = (w18*w08);
  /* #67: @29 = (@26*@28) */
  w29  = (w26*w28);
  /* #68: @29 = (@2*@29) */
  w29  = (w02*w29);
  /* #69: @13 = (@13-@29) */
  w13 -= w29;
  /* #70: @29 = 0.00066344 */
  w29 = 6.6343999999999995e-04;
  /* #71: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #72: @28 = (@3*@28) */
  w28  = (w03*w28);
  /* #73: @13 = (@13-@28) */
  w13 -= w28;
  /* #74: @28 = 0.0022203 */
  w28 = 2.2203000000000001e-03;
  /* #75: @30 = (@21*@8) */
  w30  = (w21*w08);
  /* #76: @31 = (@28*@30) */
  w31  = (w28*w30);
  /* #77: @31 = (@2*@31) */
  w31  = (w02*w31);
  /* #78: @13 = (@13-@31) */
  w13 -= w31;
  /* #79: @31 = 0.00052793 */
  w31 = 5.2793000000000002e-04;
  /* #80: @30 = (@31*@30) */
  w30  = (w31*w30);
  /* #81: @30 = (@3*@30) */
  w30  = (w03*w30);
  /* #82: @13 = (@13+@30) */
  w13 += w30;
  /* #83: (@0[2] += @13) */
  for (rr=w00+2, cs=(&w13); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #84: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #85: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #86: @13 = 2.7602e-05 */
  w13 = 2.7602000000000001e-05;
  /* #87: @30 = (@13*@6) */
  w30  = (w13*w06);
  /* #88: @30 = (@30*@10) */
  w30 *= w10;
  /* #89: @6 = (@6*@10) */
  w06 *= w10;
  /* #90: @13 = (@13*@6) */
  w13 *= w06;
  /* #91: @30 = (@30+@13) */
  w30 += w13;
  /* #92: @13 = 2.1046e-05 */
  w13 = 2.1046000000000001e-05;
  /* #93: @32 = (@13*@18) */
  w32  = (w13*w18);
  /* #94: @32 = (@32*@10) */
  w32 *= w10;
  /* #95: @30 = (@30-@32) */
  w30 -= w32;
  /* #96: @32 = 1.6506e-05 */
  w32 = 1.6506000000000001e-05;
  /* #97: @33 = (@32*@21) */
  w33  = (w32*w21);
  /* #98: @33 = (@33*@10) */
  w33 *= w10;
  /* #99: @30 = (@30+@33) */
  w30 += w33;
  /* #100: @33 = 0.0078721 */
  w33 = 7.8720999999999999e-03;
  /* #101: @33 = (@33*@10) */
  w33 *= w10;
  /* #102: @30 = (@30-@33) */
  w30 -= w33;
  /* #103: @14 = (@14*@3) */
  w14 *= w03;
  /* #104: @14 = (@14*@9) */
  w14 *= w09;
  /* #105: @30 = (@30+@14) */
  w30 += w14;
  /* #106: @4 = (@4*@2) */
  w04 *= w02;
  /* #107: @4 = (@4*@9) */
  w04 *= w09;
  /* #108: @30 = (@30+@4) */
  w30 += w04;
  /* #109: @4 = 0.00045783 */
  w04 = 4.5783000000000000e-04;
  /* #110: @4 = (@4*@9) */
  w04 *= w09;
  /* #111: @30 = (@30-@4) */
  w30 -= w04;
  /* #112: @22 = (@22*@3) */
  w22 *= w03;
  /* #113: @22 = (@22*@8) */
  w22 *= w08;
  /* #114: @30 = (@30+@22) */
  w30 += w22;
  /* #115: @25 = (@25*@2) */
  w25 *= w02;
  /* #116: @25 = (@25*@8) */
  w25 *= w08;
  /* #117: @30 = (@30-@25) */
  w30 -= w25;
  /* #118: @25 = 0.00021938 */
  w25 = 2.1938000000000000e-04;
  /* #119: @25 = (@25*@8) */
  w25 *= w08;
  /* #120: @30 = (@30+@25) */
  w30 += w25;
  /* #121: (@5[3] += @30) */
  for (rr=w05+3, cs=(&w30); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #122: @30 = 3.0088e-05 */
  w30 = 3.0088000000000001e-05;
  /* #123: @25 = (@15*@10) */
  w25  = (w15*w10);
  /* #124: @22 = (@30*@25) */
  w22  = (w30*w25);
  /* #125: @22 = (-@22) */
  w22 = (- w22 );
  /* #126: @30 = (@30*@15) */
  w30 *= w15;
  /* #127: @30 = (@30*@10) */
  w30 *= w10;
  /* #128: @22 = (@22-@30) */
  w22 -= w30;
  /* #129: @30 = 5.1765e-05 */
  w30 = 5.1765000000000003e-05;
  /* #130: @15 = (@30*@18) */
  w15  = (w30*w18);
  /* #131: @15 = (@15*@10) */
  w15 *= w10;
  /* #132: @22 = (@22+@15) */
  w22 += w15;
  /* #133: @15 = 0.00011008 */
  w15 = 1.1008000000000000e-04;
  /* #134: @4 = (@15*@21) */
  w04  = (w15*w21);
  /* #135: @4 = (@4*@10) */
  w04 *= w10;
  /* #136: @22 = (@22+@4) */
  w22 += w04;
  /* #137: @4 = 0.0046648 */
  w04 = 4.6648000000000002e-03;
  /* #138: @4 = (@4*@10) */
  w04 *= w10;
  /* #139: @22 = (@22+@4) */
  w22 += w04;
  /* #140: @12 = (@12*@3) */
  w12 *= w03;
  /* #141: @12 = (@12*@9) */
  w12 *= w09;
  /* #142: @22 = (@22-@12) */
  w22 -= w12;
  /* #143: @17 = (@17*@2) */
  w17 *= w02;
  /* #144: @17 = (@17*@9) */
  w17 *= w09;
  /* #145: @22 = (@22+@17) */
  w22 += w17;
  /* #146: @17 = 0.00029443 */
  w17 = 2.9442999999999998e-04;
  /* #147: @17 = (@17*@9) */
  w17 *= w09;
  /* #148: @22 = (@22-@17) */
  w22 -= w17;
  /* #149: @24 = (@24*@3) */
  w24 *= w03;
  /* #150: @24 = (@24*@8) */
  w24 *= w08;
  /* #151: @22 = (@22+@24) */
  w22 += w24;
  /* #152: @27 = (@27*@2) */
  w27 *= w02;
  /* #153: @27 = (@27*@8) */
  w27 *= w08;
  /* #154: @22 = (@22+@27) */
  w22 += w27;
  /* #155: @27 = 0.00028542 */
  w27 = 2.8541999999999999e-04;
  /* #156: @27 = (@27*@8) */
  w27 *= w08;
  /* #157: @22 = (@22+@27) */
  w22 += w27;
  /* #158: (@5[2] += @22) */
  for (rr=w05+2, cs=(&w22); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #159: @30 = (@30*@25) */
  w30 *= w25;
  /* #160: @13 = (@13*@6) */
  w13 *= w06;
  /* #161: @30 = (@30-@13) */
  w30 -= w13;
  /* #162: @13 = 7.2158e-05 */
  w13 = 7.2157999999999996e-05;
  /* #163: @22 = (@13*@21) */
  w22  = (w13*w21);
  /* #164: @22 = (@22*@10) */
  w22 *= w10;
  /* #165: @30 = (@30-@22) */
  w30 -= w22;
  /* #166: @22 = 0.008181 */
  w22 = 8.1810000000000008e-03;
  /* #167: @22 = (@22*@10) */
  w22 *= w10;
  /* #168: @30 = (@30+@22) */
  w30 += w22;
  /* #169: @16 = (@16*@3) */
  w16 *= w03;
  /* #170: @16 = (@16*@9) */
  w16 *= w09;
  /* #171: @30 = (@30+@16) */
  w30 += w16;
  /* #172: @20 = (@20*@2) */
  w20 *= w02;
  /* #173: @20 = (@20*@9) */
  w20 *= w09;
  /* #174: @30 = (@30+@20) */
  w30 += w20;
  /* #175: @20 = 0.000149 */
  w20 = 1.4899999999999999e-04;
  /* #176: @20 = (@20*@9) */
  w20 *= w09;
  /* #177: @30 = (@30+@20) */
  w30 += w20;
  /* #178: @26 = (@26*@3) */
  w26 *= w03;
  /* #179: @26 = (@26*@8) */
  w26 *= w08;
  /* #180: @30 = (@30+@26) */
  w30 += w26;
  /* #181: @29 = (@29*@2) */
  w29 *= w02;
  /* #182: @29 = (@29*@8) */
  w29 *= w08;
  /* #183: @30 = (@30-@29) */
  w30 -= w29;
  /* #184: @29 = 0.00044484 */
  w29 = 4.4484000000000000e-04;
  /* #185: @29 = (@29*@8) */
  w29 *= w08;
  /* #186: @30 = (@30-@29) */
  w30 -= w29;
  /* #187: (@5[1] += @30) */
  for (rr=w05+1, cs=(&w30); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #188: @32 = (@32*@6) */
  w32 *= w06;
  /* #189: @15 = (@15*@25) */
  w15 *= w25;
  /* #190: @32 = (@32+@15) */
  w32 += w15;
  /* #191: @18 = (@18*@10) */
  w18 *= w10;
  /* #192: @13 = (@13*@18) */
  w13 *= w18;
  /* #193: @32 = (@32-@13) */
  w32 -= w13;
  /* #194: @13 = 7.1607e-05 */
  w13 = 7.1606999999999994e-05;
  /* #195: @18 = (@13*@21) */
  w18  = (w13*w21);
  /* #196: @18 = (@18*@10) */
  w18 *= w10;
  /* #197: @32 = (@32-@18) */
  w32 -= w18;
  /* #198: @21 = (@21*@10) */
  w21 *= w10;
  /* #199: @13 = (@13*@21) */
  w13 *= w21;
  /* #200: @32 = (@32-@13) */
  w32 -= w13;
  /* #201: @13 = -0.0043797 */
  w13 = -4.3797000000000003e-03;
  /* #202: @13 = (@13*@10) */
  w13 *= w10;
  /* #203: @32 = (@32+@13) */
  w32 += w13;
  /* #204: @19 = (@19*@3) */
  w19 *= w03;
  /* #205: @19 = (@19*@9) */
  w19 *= w09;
  /* #206: @32 = (@32-@19) */
  w32 -= w19;
  /* #207: @23 = (@23*@2) */
  w23 *= w02;
  /* #208: @23 = (@23*@9) */
  w23 *= w09;
  /* #209: @32 = (@32+@23) */
  w32 += w23;
  /* #210: @23 = 0.0004803 */
  w23 = 4.8030000000000002e-04;
  /* #211: @23 = (@23*@9) */
  w23 *= w09;
  /* #212: @32 = (@32+@23) */
  w32 += w23;
  /* #213: @28 = (@28*@3) */
  w28 *= w03;
  /* #214: @28 = (@28*@8) */
  w28 *= w08;
  /* #215: @32 = (@32+@28) */
  w32 += w28;
  /* #216: @31 = (@31*@2) */
  w31 *= w02;
  /* #217: @31 = (@31*@8) */
  w31 *= w08;
  /* #218: @32 = (@32+@31) */
  w32 += w31;
  /* #219: @31 = -0.00016598 */
  w31 = -1.6598000000000001e-04;
  /* #220: @31 = (@31*@8) */
  w31 *= w08;
  /* #221: @32 = (@32+@31) */
  w32 += w31;
  /* #222: (@5[0] += @32) */
  for (rr=w05+0, cs=(&w32); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #223: output[0][1] = @5 */
  if (res[0]) casadi_copy(w05, 4, res[0]+3);
  /* #224: output[0][2] = @11 */
  if (res[0]) casadi_copy(w11, 4, res[0]+7);
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mirte_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mirte_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mirte_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mirte_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mirte_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mirte_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mirte_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mirte_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mirte_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mirte_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mirte_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mirte_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mirte_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mirte_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 50;
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 50*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
