/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mirte_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {7, 1, 1};

/* mirte_expl_ode_fun:(i0[3],i1[4],i2[7])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w03, w04, w05, w06, *w07=w+10, w08, w09, w10;
  const casadi_real *cs;
  /* #0: @0 = 0.00046713 */
  w00 = 4.6713000000000001e-04;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 4, w01);
  /* #2: @2 = @1[0] */
  for (rr=(&w02), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #3: @0 = (@0*@2) */
  w00 *= w02;
  /* #4: @3 = 0.00025626 */
  w03 = 2.5626000000000002e-04;
  /* #5: @4 = @1[1] */
  for (rr=(&w04), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3*@4) */
  w03 *= w04;
  /* #7: @0 = (@0+@3) */
  w00 += w03;
  /* #8: @3 = 0.00033294 */
  w03 = 3.3293999999999999e-04;
  /* #9: @5 = @1[2] */
  for (rr=(&w05), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #10: @3 = (@3*@5) */
  w03 *= w05;
  /* #11: @0 = (@0-@3) */
  w00 -= w03;
  /* #12: @3 = 0.00048742 */
  w03 = 4.8742000000000002e-04;
  /* #13: @6 = @1[3] */
  for (rr=(&w06), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #14: @3 = (@3*@6) */
  w03 *= w06;
  /* #15: @0 = (@0-@3) */
  w00 -= w03;
  /* #16: @3 = 0.00053383 */
  w03 = 5.3383000000000000e-04;
  /* #17: @7 = input[0][0] */
  casadi_copy(arg[0], 3, w07);
  /* #18: @8 = @7[2] */
  for (rr=(&w08), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #19: @9 = sin(@8) */
  w09 = sin( w08 );
  /* #20: @3 = (@3*@9) */
  w03 *= w09;
  /* #21: @3 = (@3*@2) */
  w03 *= w02;
  /* #22: @0 = (@0+@3) */
  w00 += w03;
  /* #23: @3 = 0.0008546 */
  w03 = 8.5459999999999996e-04;
  /* #24: @8 = cos(@8) */
  w08 = cos( w08 );
  /* #25: @3 = (@3*@8) */
  w03 *= w08;
  /* #26: @3 = (@3*@2) */
  w03 *= w02;
  /* #27: @0 = (@0+@3) */
  w00 += w03;
  /* #28: @3 = 0.0012309 */
  w03 = 1.2309000000000000e-03;
  /* #29: @3 = (@3*@9) */
  w03 *= w09;
  /* #30: @3 = (@3*@4) */
  w03 *= w04;
  /* #31: @0 = (@0-@3) */
  w00 -= w03;
  /* #32: @3 = 0.0013974 */
  w03 = 1.3974000000000000e-03;
  /* #33: @3 = (@3*@8) */
  w03 *= w08;
  /* #34: @3 = (@3*@4) */
  w03 *= w04;
  /* #35: @0 = (@0+@3) */
  w00 += w03;
  /* #36: @3 = 0.0016185 */
  w03 = 1.6184999999999999e-03;
  /* #37: @3 = (@3*@9) */
  w03 *= w09;
  /* #38: @3 = (@3*@5) */
  w03 *= w05;
  /* #39: @0 = (@0+@3) */
  w00 += w03;
  /* #40: @3 = 0.002975 */
  w03 = 2.9750000000000002e-03;
  /* #41: @3 = (@3*@8) */
  w03 *= w08;
  /* #42: @3 = (@3*@5) */
  w03 *= w05;
  /* #43: @0 = (@0+@3) */
  w00 += w03;
  /* #44: @3 = 0.0010424 */
  w03 = 1.0424000000000000e-03;
  /* #45: @3 = (@3*@9) */
  w03 *= w09;
  /* #46: @3 = (@3*@6) */
  w03 *= w06;
  /* #47: @0 = (@0-@3) */
  w00 -= w03;
  /* #48: @3 = 0.0031387 */
  w03 = 3.1386999999999999e-03;
  /* #49: @3 = (@3*@8) */
  w03 *= w08;
  /* #50: @3 = (@3*@6) */
  w03 *= w06;
  /* #51: @0 = (@0+@3) */
  w00 += w03;
  /* #52: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #53: @0 = 0.00084649 */
  w00 = 8.4648999999999998e-04;
  /* #54: @0 = (@0*@4) */
  w00 *= w04;
  /* #55: @3 = 0.00072714 */
  w03 = 7.2714000000000003e-04;
  /* #56: @3 = (@3*@5) */
  w03 *= w05;
  /* #57: @0 = (@0-@3) */
  w00 -= w03;
  /* #58: @3 = 0.00014791 */
  w03 = 1.4791000000000001e-04;
  /* #59: @3 = (@3*@6) */
  w03 *= w06;
  /* #60: @0 = (@0-@3) */
  w00 -= w03;
  /* #61: @3 = 0.0017139 */
  w03 = 1.7139000000000000e-03;
  /* #62: @3 = (@3*@9) */
  w03 *= w09;
  /* #63: @3 = (@3*@2) */
  w03 *= w02;
  /* #64: @0 = (@0+@3) */
  w00 += w03;
  /* #65: @3 = 0.0010843 */
  w03 = 1.0843000000000001e-03;
  /* #66: @3 = (@3*@8) */
  w03 *= w08;
  /* #67: @3 = (@3*@2) */
  w03 *= w02;
  /* #68: @0 = (@0-@3) */
  w00 -= w03;
  /* #69: @3 = 0.0012739 */
  w03 = 1.2738999999999999e-03;
  /* #70: @3 = (@3*@9) */
  w03 *= w09;
  /* #71: @3 = (@3*@4) */
  w03 *= w04;
  /* #72: @0 = (@0+@3) */
  w00 += w03;
  /* #73: @3 = 0.0028477 */
  w03 = 2.8476999999999999e-03;
  /* #74: @3 = (@3*@9) */
  w03 *= w09;
  /* #75: @3 = (@3*@5) */
  w03 *= w05;
  /* #76: @0 = (@0+@3) */
  w00 += w03;
  /* #77: @3 = 0.00051979 */
  w03 = 5.1979000000000001e-04;
  /* #78: @3 = (@3*@8) */
  w03 *= w08;
  /* #79: @3 = (@3*@5) */
  w03 *= w05;
  /* #80: @0 = (@0-@3) */
  w00 -= w03;
  /* #81: @3 = 0.002315 */
  w03 = 2.3149999999999998e-03;
  /* #82: @3 = (@3*@9) */
  w03 *= w09;
  /* #83: @3 = (@3*@6) */
  w03 *= w06;
  /* #84: @0 = (@0+@3) */
  w00 += w03;
  /* #85: @3 = 0.0016072 */
  w03 = 1.6072000000000000e-03;
  /* #86: @3 = (@3*@8) */
  w03 *= w08;
  /* #87: @3 = (@3*@6) */
  w03 *= w06;
  /* #88: @0 = (@0+@3) */
  w00 += w03;
  /* #89: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #90: @0 = -0.008273 */
  w00 = -8.2730000000000008e-03;
  /* #91: @0 = (@0*@2) */
  w00 *= w02;
  /* #92: @3 = 0.0058674 */
  w03 = 5.8674000000000000e-03;
  /* #93: @3 = (@3*@4) */
  w03 *= w04;
  /* #94: @0 = (@0+@3) */
  w00 += w03;
  /* #95: @3 = 0.0082594 */
  w03 = 8.2594000000000001e-03;
  /* #96: @3 = (@3*@5) */
  w03 *= w05;
  /* #97: @0 = (@0+@3) */
  w00 += w03;
  /* #98: @3 = 0.0048492 */
  w03 = 4.8491999999999997e-03;
  /* #99: @3 = (@3*@6) */
  w03 *= w06;
  /* #100: @0 = (@0-@3) */
  w00 -= w03;
  /* #101: @3 = 2.0735e-05 */
  w03 = 2.0735000000000001e-05;
  /* #102: @10 = sq(@2) */
  w10 = casadi_sq( w02 );
  /* #103: @3 = (@3*@10) */
  w03 *= w10;
  /* #104: @0 = (@0-@3) */
  w00 -= w03;
  /* #105: @3 = 3.034e-05 */
  w03 = 3.0340000000000001e-05;
  /* #106: @3 = (@3*@2) */
  w03 *= w02;
  /* #107: @3 = (@3*@4) */
  w03 *= w04;
  /* #108: @0 = (@0-@3) */
  w00 -= w03;
  /* #109: @3 = 1.7929e-05 */
  w03 = 1.7929000000000001e-05;
  /* #110: @3 = (@3*@2) */
  w03 *= w02;
  /* #111: @3 = (@3*@5) */
  w03 *= w05;
  /* #112: @0 = (@0+@3) */
  w00 += w03;
  /* #113: @3 = 4.8351e-05 */
  w03 = 4.8350999999999998e-05;
  /* #114: @3 = (@3*@2) */
  w03 *= w02;
  /* #115: @3 = (@3*@6) */
  w03 *= w06;
  /* #116: @0 = (@0-@3) */
  w00 -= w03;
  /* #117: @3 = 2.2017e-05 */
  w03 = 2.2016999999999999e-05;
  /* #118: @10 = sq(@4) */
  w10 = casadi_sq( w04 );
  /* #119: @3 = (@3*@10) */
  w03 *= w10;
  /* #120: @0 = (@0-@3) */
  w00 -= w03;
  /* #121: @3 = 7.4116e-05 */
  w03 = 7.4116000000000007e-05;
  /* #122: @3 = (@3*@4) */
  w03 *= w04;
  /* #123: @3 = (@3*@5) */
  w03 *= w05;
  /* #124: @0 = (@0+@3) */
  w00 += w03;
  /* #125: @3 = 5.0373e-06 */
  w03 = 5.0373000000000000e-06;
  /* #126: @3 = (@3*@4) */
  w03 *= w04;
  /* #127: @3 = (@3*@6) */
  w03 *= w06;
  /* #128: @0 = (@0+@3) */
  w00 += w03;
  /* #129: @3 = 5.838e-06 */
  w03 = 5.8379999999999998e-06;
  /* #130: @10 = sq(@5) */
  w10 = casadi_sq( w05 );
  /* #131: @3 = (@3*@10) */
  w03 *= w10;
  /* #132: @0 = (@0+@3) */
  w00 += w03;
  /* #133: @3 = 5.6774e-06 */
  w03 = 5.6774000000000001e-06;
  /* #134: @3 = (@3*@5) */
  w03 *= w05;
  /* #135: @3 = (@3*@6) */
  w03 *= w06;
  /* #136: @0 = (@0-@3) */
  w00 -= w03;
  /* #137: @3 = 2.7656e-05 */
  w03 = 2.7656000000000001e-05;
  /* #138: @10 = sq(@6) */
  w10 = casadi_sq( w06 );
  /* #139: @3 = (@3*@10) */
  w03 *= w10;
  /* #140: @0 = (@0+@3) */
  w00 += w03;
  /* #141: @3 = 0.0015492 */
  w03 = 1.5491999999999999e-03;
  /* #142: @3 = (@3*@9) */
  w03 *= w09;
  /* #143: @3 = (@3*@2) */
  w03 *= w02;
  /* #144: @0 = (@0+@3) */
  w00 += w03;
  /* #145: @3 = 0.0037682 */
  w03 = 3.7682000000000002e-03;
  /* #146: @3 = (@3*@8) */
  w03 *= w08;
  /* #147: @3 = (@3*@2) */
  w03 *= w02;
  /* #148: @0 = (@0+@3) */
  w00 += w03;
  /* #149: @3 = 0.00099873 */
  w03 = 9.9872999999999997e-04;
  /* #150: @3 = (@3*@9) */
  w03 *= w09;
  /* #151: @3 = (@3*@4) */
  w03 *= w04;
  /* #152: @0 = (@0+@3) */
  w00 += w03;
  /* #153: @3 = 0.0029068 */
  w03 = 2.9068000000000002e-03;
  /* #154: @3 = (@3*@8) */
  w03 *= w08;
  /* #155: @3 = (@3*@4) */
  w03 *= w04;
  /* #156: @0 = (@0+@3) */
  w00 += w03;
  /* #157: @3 = 0.00080454 */
  w03 = 8.0453999999999996e-04;
  /* #158: @3 = (@3*@9) */
  w03 *= w09;
  /* #159: @3 = (@3*@5) */
  w03 *= w05;
  /* #160: @0 = (@0-@3) */
  w00 -= w03;
  /* #161: @3 = 0.0029993 */
  w03 = 2.9992999999999999e-03;
  /* #162: @3 = (@3*@8) */
  w03 *= w08;
  /* #163: @3 = (@3*@5) */
  w03 *= w05;
  /* #164: @0 = (@0-@3) */
  w00 -= w03;
  /* #165: @3 = 0.0015042 */
  w03 = 1.5042000000000000e-03;
  /* #166: @3 = (@3*@9) */
  w03 *= w09;
  /* #167: @3 = (@3*@6) */
  w03 *= w06;
  /* #168: @0 = (@0-@3) */
  w00 -= w03;
  /* #169: @3 = 0.0037508 */
  w03 = 3.7507999999999999e-03;
  /* #170: @3 = (@3*@8) */
  w03 *= w08;
  /* #171: @3 = (@3*@6) */
  w03 *= w06;
  /* #172: @0 = (@0-@3) */
  w00 -= w03;
  /* #173: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mirte_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mirte_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mirte_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mirte_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mirte_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mirte_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mirte_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mirte_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}

CASADI_SYMBOL_EXPORT int mirte_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 16*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
