#ifndef ACADOS_INTERFACE_H
#define ACADOS_INTERFACE_H

#include <Eigen/Dense>
#include "acados_solver_mirte.h"  // Generated by Acados
#include <stdexcept>
#include <iostream>

using Eigen::MatrixXd;
using Eigen::VectorXd;

class AcadosInterface {
public:
    AcadosInterface();
    ~AcadosInterface();

    bool initialise();
    void setState(const VectorXd& x, const VectorXd& rci, const VectorXd& LB_tightened, const VectorXd& UB_tightened);
    void setReference(const MatrixXd& x_ref_traj, const VectorXd& LB_tightened, const VectorXd& UB_tightened);
    VectorXd solve();
    VectorXd getx0();
    
private:
    mirte_solver_capsule* capsule_;
    Eigen::VectorXd param_; 
    ocp_nlp_config* nlp_config_;
    ocp_nlp_dims* nlp_dims_;
    ocp_nlp_in* nlp_in_;
    ocp_nlp_out* nlp_out_;
};

#endif